# Generated by Django 5.2.1 on 2025-05-31 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='URL-идентификатор')),
                ('text', models.TextField(verbose_name='Текст')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название раздела')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-идентификатор')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.CreateModel(
            name='ArticleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной раздел')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article', verbose_name='Статья')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.section', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Раздел статьи',
                'verbose_name_plural': 'Разделы статей',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='sections',
            field=models.ManyToManyField(default='temp-slug', through='articles.ArticleSection', through_fields=('article', 'section'), to='articles.section', verbose_name='Разделы'),
        ),
        migrations.AddConstraint(
            model_name='articlesection',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('article', 'is_primary'), name='unique_primary_section_per_article'),
        ),
    ]
