# Generated by Django 5.2.1 on 2025-05-31 14:01

from django.db import migrations
from django.utils.text import slugify

def generate_slugs(apps, schema_editor):
    Article = apps.get_model('articles', 'Article')
    for article in Article.objects.all():
        article.slug = slugify(article.title)
        article.save()


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(generate_slugs),
    ]
