# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение датчиков
GET {{baseUrl}}/sensors/
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/sensors/
Content-Type: application/json

{
  "name": "ESP32",
  "description": "Датчик на кухне за холодильником"
}

###

# обновление датчика
PATCH {{baseUrl}}/sensors/3/
Content-Type: application/json

{
  "name": "Датчик на балконе",
  "description": "Перенес датчик на балкон"
}

###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor": 3,
  "temperature": 12.1
}

###

# добавление измерения c фото
POST {{baseUrl}}/measurements/
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="sensor"

3
--MyBoundary
Content-Disposition: form-data; name="temperature"

11.0
--MyBoundary
Content-Disposition: form-data; name="image"; filename="photo.jpg"
Content-Type: image/jpeg

< ./media/measurements/photo.jpg
--MyBoundary--

###

# получение информации по датчику
GET {{baseUrl}}/sensors/1/
Content-Type: application/json
