# примеры API-запросов

@baseUrl = http://localhost:8000/api/v1

# создание продукта
POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "Капуста",
  "description": "Молодая небольшая"
}

###

# получение продуктов
GET {{baseUrl}}/products/
Content-Type: application/json

###

# обновление продукта
PATCH {{baseUrl}}/products/4/
Content-Type: application/json

{
  "title": "Морковь",
  "description": "Крупная"
}

###

# удаление продукта
DELETE {{baseUrl}}/products/5/
Content-Type: application/json

###

# поиск продуктов по названию и описанию
GET {{baseUrl}}/products/?search=помидор
Content-Type: application/json

###

# создание склада
POST {{baseUrl}}/stocks/
Content-Type: application/json

{
  "address": "Ул.Складская, дом 14",
  "positions": [
    {
      "product": 3,
      "quantity": 100,
      "price": 100
    }
  ]
}

###

# обновляем записи на складе
PATCH {{baseUrl}}/stocks/4/
Content-Type: application/json

{
  "positions": [
    {
      "product": 3,
      "quantity": 300,
      "price": 310
    },
    {
      "product": 7,
      "quantity": 150,
      "price": 145
    }
  ]
}

###

# получение состояния по складам
GET {{baseUrl}}/stocks/
Content-Type: application/json

###

# поиск складов, где есть определенный продукт
GET {{baseUrl}}/stocks/?products=2
Content-Type: application/json

###

# поиск складов, где есть определенный продукт
GET {{baseUrl}}/stocks/?search=помид
Content-Type: application/json
